blank_issues_enabled: false
contact_links:
  - name: "💬 Fragen & Diskussionen"
    url: https://github.com/baerenbude-org/hexchat/discussions
    about: "Für allgemeine Fragen zur Konfiguration, Skripten oder Netzwerken."
